# azure-pipelines.yml
trigger:
- main

pool:
  name: ss-vm-agent-pool

variables:
  imageName: 'ecommerce-flask'

steps:
- checkout: self

- task: DockerInstaller@0
  displayName: 'Install Docker'

- task: Docker@2
  displayName: 'Login to ACR'
  inputs:
    containerRegistry: 'ACR-ServiceConnection'
    command: 'login'

- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    containerRegistry: 'ACR-ServiceConnection'
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest

- task: PublishPipelineArtifact@1
  displayName: 'Publish Artifact for CD'
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: drop
