# CD Pipeline - Deploy to Azure Kubernetes Service

trigger: none  # CD pipeline does NOT trigger on code changes

resources:
  pipelines:
  - pipeline: ciPipeline            # Alias for CI pipeline resource
    source: ci-pipeline             # CI pipeline name
    trigger:
      branches:
        include:
        - main

variables:
  dockerRegistryServiceConnection: '17d0aa1f-40a2-4606-8d53-2bf2871d728c'
  imageRepository: 'capstone'
  containerRegistry: 'ecomacr598.azurecr.io'
  tag: '$(resources.pipeline.ciPipeline.runName)'  # Get tag from CI pipeline
  imagePullSecret: 'ecomacr5981330f57c-auth'

stages:
- stage: Deploy
  displayName: Deploy stage

  jobs:
  - deployment: Deploy
    displayName: Deploy to AKS
    pool:
      name: ss-vm-agent-pool
    environment: 'capstone.default'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: ciPipeline
            artifact: manifests

          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(Pipeline.Workspace)/ciPipeline/manifests/deployment.yml
                $(Pipeline.Workspace)/ciPipeline/manifests/service.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)
