# cd-pipeline.yml
trigger: none  # No GitHub trigger directly

resources:
  pipelines:
    - pipeline: ciPipeline                # Alias for CI
      source: ci-pipeline                 # CI pipeline name in Azure DevOps
      trigger:
        branches:
          include:
            - main

stages:
- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: []
  condition: succeeded()
  jobs:
  - job: DeployToAKS
    displayName: Deploy Flask App to AKS
    pool:
      name: ss-vm-agent-pool

    steps:
    - download: ciPipeline
      artifact: drop

    - task: Kubernetes@1
      displayName: Deploy Flask App
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscription: 'AKS-ServiceConnection-1'
        azureResourceGroup: 'ss-rg'
        kubernetesCluster: 'ss-aks-cluster'
        namespace: default
        command: apply
        useConfigurationFile: true
        configuration: |
          k8s/app-deployment.yaml
          k8s/app-service.yaml
