# azure-pipelines.yml
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'ecommerce-flask'

steps:
- task: Checkout@1

- task: DockerInstaller@0
  displayName: 'Install Docker'

- task: Docker@2
  displayName: 'Login to ACR'
  inputs:
    containerRegistry: 'ACR-ServiceConnection'  # Replace this in next step
    command: 'login'

- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    containerRegistry: 'ACR-ServiceConnection'  # Replace this
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest
