trigger:
  branches:
    include:
      - main

pool:
  name: ss-vm-agent-pool

variables:
  - group: capstone-variables
  - name: imageName
    value: sethumadavacr.azurecr.io/capstone:$(Build.BuildId)
  - name: azureServiceConnection
    value: 'terraform-service-connection'
  - name: acrServiceConnection
    value: 'acr-service-connection'
  - name: sonarConnection
    value: 'sonar-capstone'
  - name: terraformDirectory
    value: '.'

# =======================
# 1. SonarCloud Analysis
# =======================
stages:
- stage: SonarCloud
  displayName: 'SonarCloud Code Analysis'
  jobs:
    - job: Sonar
      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.x'

        - script: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install pytest pytest-cov
            pytest --cov=Market --cov-report=xml
          displayName: 'Install dependencies & Run Tests with Coverage'

        - task: SonarCloudPrepare@1
          inputs:
            SonarCloud: $(sonarConnection)
            organization: 'devuser130746'
            scannerMode: 'CLI'
            configMode: 'manual'
            cliProjectKey: 'capstone'
            cliProjectName: 'capstone'
            cliSources: '.'
            extraProperties: |
              sonar.python.coverage.reportPaths=coverage.xml

        - script: |
            sudo apt-get update
            sudo apt-get install -y unzip wget
            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
            unzip sonar-scanner-cli-5.0.1.3006-linux.zip
            export PATH=$(pwd)/sonar-scanner-5.0.1.3006-linux/bin:$PATH
            sonar-scanner \
              -Dsonar.projectKey=capstone \
              -Dsonar.organization=devuser130746 \
              -Dsonar.sources=. \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$(SONAR_TOKEN)
          displayName: 'Install and Run SonarCloud Scanner'

        - task: SonarCloudPublish@1
          inputs:
            pollingTimeoutSec: '300'

# ============================
# 2. Docker Build & Push Stage
# ============================
- stage: BuildAndPush
  displayName: 'Build and Push Docker Image'
  dependsOn: SonarCloud
  jobs:
    - job: Build
      steps:
        - task: Docker@2
          displayName: 'Login to ACR'
          inputs:
            command: login
            containerRegistry: $(acrServiceConnection)

        - task: Docker@2
          displayName: 'Build Docker Image'
          inputs:
            command: build
            Dockerfile: '**/Dockerfile'
            tags: |
              $(imageName)

        - task: Docker@2
          displayName: 'Push Docker Image'
          inputs:
            command: push
            tags: |
              $(imageName)

# =========================================
# 3. Deploy to Two AKS Clusters (Same RG)
# =========================================
- stage: DeployToAKS
  displayName: 'Deploy to Both AKS Clusters'
  dependsOn: BuildAndPush
  jobs:
    - job: DeployToCluster1
      displayName: 'Deploy to AKS Cluster 1 (VNET1)'
      steps:
        - task: AzureCLI@2
          displayName: 'Get AKS Credentials - Cluster 1'
          inputs:
            azureSubscription: $(azureServiceConnection)
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              az aks get-credentials --resource-group sethu-rg --name sethu-aks-cluster-vnet1 --overwrite-existing

        # - script: |
        #     sed -i "s|__CONTAINER_TAG__|$(imageName)|g" manifests/deployment.yml
        #     kubectl apply -f manifests/
        #   displayName: 'Deploy to AKS Cluster 1'
        - script: |
            imageName="sethumadavacr.azurecr.io/capstone:$(Build.BuildId)"
            echo "Using image: $imageName"
            sed -i "s|__IMAGE_NAME__|$imageName|g" manifests/deployment.yml
            cat manifests/deployment.yml
          displayName: "Inject full image name"


    - job: DeployToCluster2
      displayName: 'Deploy to AKS Cluster 2 (VNET2)'
      dependsOn: DeployToCluster1
      steps:
        - task: AzureCLI@2
          displayName: 'Get AKS Credentials - Cluster 2'
          inputs:
            azureSubscription: $(azureServiceConnection)
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              az aks get-credentials --resource-group sethu-rg --name sethu-aks-cluster-vnet2 --overwrite-existing

        - script: |
            sed -i "s|__CONTAINER_TAG__|$(imageName)|g" manifests/deployment.yml
            kubectl apply -f manifests/
          displayName: 'Deploy to AKS Cluster 2'
