apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
        - name: capstone
          image: __IMAGE_NAME__
          #image: sethumadavacr.azurecr.io/capstone:__CONTAINER_TAG__  # Placeholder for pipeline replacement
          imagePullPolicy: Always
          ports:
            - containerPort: 80
