apiVersion : apps/v1
kind: Deployment
metadata:
  name: capstone 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone 
    spec:
      containers:
        - name: capstone 
          image: ssacr598.azurecr.io/capstone:latest
          ports:
          - containerPort: 80
      imagePullSecrets:
        - name: ssacr-auth