apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: keyvaultaks
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"             # set "true" if using Managed Identity
    useVMManagedIdentity: "true"        # true if your AKS nodepool MSI has access to Key Vault
    userAssignedIdentityID: ""          # (Optional) required if using User Assigned MSI
    keyvaultName: ecom-kv               # 🔹 Replace with your Azure Key Vault name
    cloudName: ""                       # Leave empty for Azure Public Cloud
    objects: |
      array:
        - |
          objectName: db-username       # 🔹 secret name in Key Vault
          objectType: secret            # secret / key / cert
        - |
          objectName: db-password
          objectType: secret
    tenantId: "<YOUR_TENANT_ID>"        # 🔹 Replace with your Azure Tenant ID
