apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-container
          image: ecomacr598.azurecr.io/ecommerce-flask:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_SERVER
              value: "ecom-sql-serve.database.windows.net"
            - name: DB_NAME
              value: "ecomdb"
            - name: DB_USER
              value: "CloudSA4beea99f"
            - name: DB_PASS
              value: "Sethu@1111"
